import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased`}>
        {/* header */}
        <main className="min-h-screen">{children}</main>
      </body>
      {/* footer */}
      <footer className="py-4">
        <div className="container mx-auto text-center text-gray-500">
          <p className="text-md"> Made with ❤️ by Xtra</p>
        </div>
      </footer>
    </html>
  );
}
